### ISSUE TITLE
Import Volatile updates since 2016-10-07

### ISSUE THREAD

**Issue by RuanEllis** [alces-software/gridware-packages-main#29]

**Comment by andrewprovis** [comment]
2016-10-11
- apps-iozone-v3.420
- apps-fastqc-v0.11.3
- apps-fastuniq-v1.1
- apps-plink-v1.90.150618
- apps-macs-v2.1.0.20150731
- apps-cufflinks-v2.2.2.20150701
- apps-bowtie2-v2.2.6
- apps-abyss-v1.5.2

**Comment by andrewprovis** [comment]
2016-10-13
- apps-anges-v1.01
- apps-imb-v4.0

**Comment by mjtko** [comment]
2016-10-20
- apps-scala-2.11.8

**Comment by andrewprovis** [comment]
2016-10-21
- apps-cap3-20150211
- apps-ncbiblast-2.2.30

**Comment by andrewprovis** [comment]
2016-10-24
- apps-multiztba-102109

**Comment by andrewprovis** [comment]
2016-10-25
- apps-circos-0.66

**Comment by andrewprovis** [comment]
2016-10-26
- apps-express-1.5.1

**Comment by andrewprovis** [comment]
2016-10-27
- apps-fgwas-0.3.5

**Comment by RuanEllis** [comment]
2016-10-27
- apps-bismark-0.16.3

**Comment by andrewprovis** [comment]
2016-10-28
- apps-wise2-2.2.3

**Comment by andrewprovis** [comment]
2016-11-01
- apps-ncbiblast-2.2.29
- apps-cegma-2.5.0

**Comment by RuanEllis** [comment]
2016-11-02
- apps-trimgalore-0.4.2

**Comment by andrewprovis** [comment]
2016-11-02
- apps-soapdenovo-2r240

**Comment by RuanEllis** [comment]
2016-11-07
- apps-fastml-3.1
- apps-gubbins-1.4.3
- apps-opempi-1.10.2
- apps-geneid-1.4.4

**Comment by andrewprovis** [comment]
2016-11-07
- libs-bioperl-1.6.923
