### ISSUE TITLE
Import Volatile updates since 2016-11-09

### ISSUE THREAD

**Issue by andrewprovis** [alces-software/gridware-packages-main#31]

**Comment by andrewprovis** [comment]
2016-11-09
- apps-gerp-20110522
- apps-grinder-0.5.3

**Comment by andrewprovis** [comment]
2016-11-11
- apps-gromacs-4.6.5

**Comment by andrewprovis** [comment]
2016-11-15
- apps-r-3.0.0
- apps-phantompeakqualtools-1.1
- apps-raxml-8.2.4
- apps-scala-2.11.8

**Comment by andrewprovis** [comment]
2016-11-25

- apps-maqview-0.2.5
- apps-iozone-3.420

**Comment by mjtko** [comment]
2016-11-28

* apps-bazel-0.4.0

**Comment by andrewprovis** [comment]
2016-11-29

- libs-trilinos-12.10.1

**Comment by andrewprovis** [comment]
2016-12-02

- apps-python3-3.5.2
- apps-samtools-1.3.1
- apps-htslib-1.3.2

**Comment by andrewprovis** [comment]
2016-12-08

- compilers-gcc-4.4.7
- apps-hapflk-1.2
- apps-bwa-0.7.15

**Comment by andrewprovis** [comment]
2016-12-09

- apps-hpl-2.1
- apps-R-3.3.2

**Comment by andrewprovis** [comment]
2016-12-14

- libs-mpfr-3.1.4
- libs-mpfr-3.1.5
- apps-vcftools-0.1.14

**Comment by andrewprovis** [comment]
2016-12-15

- libs-expat-2.2.0
- apps-relion-2.0.20161005
- apps-rstudio-1.1.11

**Comment by andrewprovis** [comment]
2016-12-21

- libs-opengv-20161102
- libs-gflags-2.0

**Comment by andrewprovis** [comment]
2016-12-22

- libs-glog-0.3.3
